sudo: false
language: ruby
cache: bundler

rvm:
  - 2.1.9
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0

before_install:
  - gem install bundler --no-document

script:
  - bundle exec rubocop --display-cop-names --extra-details 
  - bundle exec rspec
