sudo: false
language: ruby
cache: bundler

rvm:
  - 2.1.9
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

before_install:
  - gem install bundler --no-document

script:
  - bundle exec rubocop --display-cop-names --extra-details 
  - bundle exec rspec
