sudo: false
language: ruby
cache: bundler

rvm:
  - 2.1.9
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

before_install:
  - gem install bundler --version 1.14.6 --no-document

script:
  - bundle exec rubocop
  - bundle exec rspec
